### ISSUE TITLE
Current release is still 1.0.0

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/algorithm.py#15]
We should make a new release, two PRs with code and docs improvements have been merged since 1.0.0 (#10 in particular would help for https://github.com/AspenWeb/pando.py/issues/548).

**Comment by Changaco** [comment]
Ping @whit537.

**Comment by whit537** [comment]
👍

What do you need from me? Access on PyPI and Heroku, ya?

**Comment by Changaco** [comment]
Just PyPI access. Heroku would be for https://github.com/AspenWeb/aspen.io I assume.

My PyPI username is Changaco, it looks like you can me as an owner or maintainer on [the Roles page](https://pypi.python.org/pypi?:action=role_form&package_name=algorithm).

**Comment by Changaco** [comment]
1.1.0 is tagged and uploaded to PyPI.
